### ISSUE TITLE
Furbot   兽云祭接口 返回code514问题

### ISSUE THREAD

**Issue by zxmacc** [initialencounter/mykoishi#24]
系统: Ubuntu 20.04.6 LTS   （ARM）
机器：甲骨文韩国春川ARM
插件Furbot   兽云祭接口

插件功能都没法使用，发送fur会产生以下报错，请问是机子在国外的原因吗
```
2023-07-21 17:13:00 [E] furbot AxiosError: Request failed with status code 514
                            at settle (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:1268:12)
                            at IncomingMessage.handleStreamEnd (/koishi/node_modules/cordis-axios/node_modules/axios/dist/node/axios.cjs:2446:11)
                            at IncomingMessage.emit (node:events:525:35)
                            at endReadableNT (node:internal/streams/readable:1359:12)
                            at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by initialencounter** [comment]
网络问题吧，现在还会报错吗？
