### ISSUE TITLE
adapter-wechat4u 报错'1101' == 0

### ISSUE THREAD

**Issue by Azerz** [initialencounter/mykoishi#54]
可以返回登陆成功，但发消息无反应。尝试过删除data/wechat4u配置文件依然无法使用
-------
2024-07-19 21:15:00 [W] market fetch https://registry.npmmirror.com/@koishijs/plugin-actions failed
2024-07-19 21:18:06 [I] wechat4u Scan QR Code to login: 3
                        https://wechaty.js.org/qrcode/https%3A%2F%2Flogin.weixin.qq.com%2Fl%2FobUVcRUC3w%3D%3D
2024-07-19 21:18:28 [W] app AssertionError [ERR_ASSERTION]: '1101' == 0
                            at Object.equal (/home/wolfe/.koishi/data/instances/default/node_modules/wechat4u/lib/util/global.js:69:24)
                            at /home/wolfe/.koishi/data/instances/default/node_modules/wechat4u/lib/core.js:410:24
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
-------
System:

OS: Linux 5.15 Ubuntu 22.04.4 LTS 22.04.4 LTS (Jammy Jellyfish)

CPU: (4) x64 Intel(R) Xeon(R) Platinum 8336C CPU @ 2.30GHz

Binaries:

Node: 20.12.2

Yarn: 4.1.1

Koishi:

Core: 4.17.10

Console: 5.28.4

Koishi Desktop: 1.1.3
-------

**Comment by initialencounter** [comment]
koishi根目录还有一个配置文件，也删了试试

**Comment by Azerz** [comment]
手机端扫码登录成功，不切换用户使用正常 。但是只要手机端一切换用户即无法使用

**Comment by initialencounter** [comment]
不太清楚，我手机用的微信多开

**Comment by Azerz** [comment]
好吧，初步看来是扫码登陆后手机不能切换用户。感谢
