### ISSUE TITLE
出现报错[ERR_ASSERTION]: 3 == 0

### ISSUE THREAD

**Issue by Marchccc** [initialencounter/mykoishi#57]
app AssertionError [ERR_ASSERTION]: 3 == 0
    at Object.equal (/koishi/node_modules/wechat4u/lib/util/global.js:69:24)
    at /koishi/node_modules/wechat4u/lib/core.js:446:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

请问这个具体是什么原因导致的？有没有解决思路？

**Comment by initialencounter** [comment]
这是正常滴，上游的wechaty两年没更新了
